#### <u>Question 1

Disply the following sentence in bold font face <br>
"This is first lab of Applied Computational Statics"


ANS:-

**This is fisrt lab of Applied Computational Statics**,<br>
Clue: Using double asterisk mark both side -**bold text**

#### <u>Question 2

Recreate the following bullet points in  Jupyter notebook markdown cell:<br>
markdown cell : markdown <br>
code cell: Python code <br>
Subject: Statistics 

ANS-
- **Markdown cell**: markdown  
- **Code cell**: Python code  
- **Subject**: Statistics


#### <u>Question 3

**Run the following code in two different Jupyter notebook cells. Run one cell as a code cell. Run the other cell as a Markdown cell. Why is the output different?**

In [3]:
#using print() function 
print("The Northcap University")


The Northcap University


#using print() function 
print("The Northcap University")


ANS:

-When we use cell as code it execute the code and give us the output as `'The Northcap University'`
whereas when we use the cell as markdown it doesn't execute anything as it use for formatting text only




#### <u>Question 4

**Use *float()* to create a number from a string like '12.34'. Make sure the result is really a number!**

In [9]:
#As '12.34' is already in string type we use float() function to convert string to float
#this is explicit conversion (also known as type casting).
num = float('12.34')
print(num)  # Output: 12.34
print(type(num))  # Checking the data type to confirm it's a number


12.34
<class 'float'>


#### <u>Question 5

Write a simple Python program that displays the following **powers of 2**, one per line: $$2^1, 2^2, 2^3, 2^4, 2^5, 2^6, 2^7, 2^8$$

In [8]:
for i in range(1, 9):  # Loop from 1 to 8
  print(f"2^{i} = {2**i}")  # Calculate and display power of 2



2^1 = 2
2^2 = 4
2^3 = 8
2^4 = 16
2^5 = 32
2^6 = 64
2^7 = 128
2^8 = 256


#### <u>Question 6


**Write a Python program that allows the user to enter any integer value, and displays the value of 2 raised to that power. Your program should function as shown below.**

What power of two? 10

Two to the power of 10 is 1024

In [10]:
# Ask the user for input
power = int(input("What power of two? "))

# Calculate 2 raised to the given power
result = 2 ** power

# Display the result
print(f"Two to the power of {power} is {result}")


What power of two?  10


Two to the power of 10 is 1024


#### <u>Question 7


**Write a python program that prompt the user to enter a list of numbers and returns the index of the smallest element in a list of integers.**

**If the number of occurrence of smallest element is greater than 1, return the smallest index.**

In [15]:
# Get input from the user
numbers = list(map(int, input("Enter numbers separated by spaces: ").split()))

# Find the smallest number and its index
min_index = numbers.index(min(numbers))

# Display the result
print(f"The smallest element is at index {min_index}")


Enter numbers separated by spaces:  2 8 3 5 8 954 3 0 3


The smallest element is at index 7


#### <u>Question 8



**Losing Your Head over Chess**

The game of chess is generally believed to have been invented in India in the sixth century for a ruling king by one of his subjects. The king was supposedly very delighted with the game and asked the subject what he wanted in return. The subject, being clever, asked for one grain of wheat on the first square, two grains of wheat on the second square, four grains of wheat on the third square, and so forth, doubling the amount on each next square. The king thought that this was a modest reward for such an invention. However, the total amount of wheat would have been more than 1,000 times the current world production.

**Develop and test a Python program that calculates how much wheat this would be in pounds, using the fact that a grain of wheat weighs approximately $1/7,000$ of a pound.**

In [28]:
# Constants
grains_per_pound = 1 / 7000  # Weight of one grain in pounds
squares_on_chessboard = 64   # A standard chessboard has 64 squares

# Calculate the total number of grains (sum of a geometric series)
total_grains = 2**squares_on_chessboard - 1

# Calculate the total weight in pounds
total_weight_in_pounds = total_grains * grains_per_pound

# Display the result
print(f"Total grains of wheat: {total_grains}")
print(f"Total weight in pounds: {total_weight_in_pounds:.2e} pounds")


Total grains of wheat: 18446744073709551615
Total weight in pounds: 2.64e+15 pounds


#### <u>Question 9

**Write a Python program that prompts the user for two floating-point values and displays the result of the first number divided by the second, in integer only.**

In [18]:
# Prompt the user for two floating-point values
num1 = float(input("Enter the first floating-point number: "))
num2 = float(input("Enter the second floating-point number: "))

# Perform the division and display the result as an integer
result = int(num1 / num2)

# Display the result
print(f"The result of {num1} divided by {num2} is {result} (integer only).")


Enter the first floating-point number:  7.2
Enter the second floating-point number:  1.3


The result of 7.2 divided by 1.3 is 5 (integer only).


#### <u>Question 10

**Use NumPy to generate a random number between 0 and 1**

In [17]:
import numpy as np

# Generate a random number between 0 and 1
random_number = np.random.rand()

# Display the result
print(random_number)


0.13420524026873037


#### <u>Question 11

**Create an array of 20 linearly spaced points between 0 and 1**

In [19]:
import numpy as np

# Create an array of 20 linearly spaced points between 0 and 1
points = np.linspace(0, 1, 20)

# Display the array
print(points)


[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


#### <u>Question 12

**Create following array using numpy and simply sum of rows and sum of coloumns** <br>
[[ 1,  2,  3,  4,  5],<br>
 [ 6,  7,  8,  9, 10], <br>
 [11, 12, 13, 14, 15], <br>
 [16, 17, 18, 19, 20], <br>
 [21, 22, 23, 24, 25]]

In [23]:
import numpy as np

# Create the 5x5 array
array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])

# Sum of rows
sum_rows = np.sum(array, axis=1)

# Sum of columns
sum_columns = np.sum(array, axis=0)

# Display the array, sum of rows and sum of columns
print(f"The array is :\n{array}")
print(f"the sum of rows is :{sum_rows}")
print(f"the sum of  is columns is: {sum_columns}")


The array is :
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
the sum of rows is :[ 15  40  65  90 115]
the sum of  is columns is: [55 60 65 70 75]


**Evaluate each of the following Python expressions first by hand and then verify using jupyter notebook. Assume any value of $(d1,d2,d3)$** <br>
<b>1.</b>	$(d1 + d2 + d3) / 3$ <br>
<b>2.</b>	$d1 + d2 + (d3 / 3)$<br>
<b>3.</b>	$3 * (d1 + d2) * (d1 - d3)$

In [27]:
d1, d2, d3 = 10, 20, 30

# Expression 1
result_1 = (d1 + d2 + d3) / 3
print(result_1)  # Expected: 20

# Expression 2
result_2 = d1 + d2 + (d3 / 3)
print(result_2)  # Expected: 40

# Expression 3
result_3 = 3 * (d1 + d2) * (d1 - d3)
print(result_3)  # Expected: -1800


20.0
40.0
-1800
